server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:12100/platform?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: bunny
    password: bunny
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.qq.com
    port: 587
    username: 480075988@qq.com
    password: vamuttsxbesqbgcg  # 这是你的 QQ 邮箱授权码
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    root: info
    com.platform: debug
