server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:12100/platform?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: bunny
    password: bunny
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    root: info
    com.platform: debug
