spring:
  datasource:
    url: jdbc:mysql://localhost:12100/platform?useSSL=false&serverTimezone=UTC
    username: bunny
    password: bunny
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080
